#!/usr/bin/env bash
#
# AI-guided README authoring for a specific repo.
#
# Writes or rewrites a README according to caller-specified audience, tone,
# sections, and emphasis. Respects existing LTS and AI marker blocks when
# PRESERVE_HUMAN=true.
#
# Required env vars:
#   GH_TOKEN       — PAT with repo + models:read scopes
#   GITHUB_OWNER   — org containing the target repo
#   TARGET_REPO    — repo name to write the README for
#
# Optional env vars:
#   AUDIENCE       — developers | end-users | ops-sysadmins | mixed (default: developers)
#   TONE           — technical | friendly | minimal (default: technical)
#   SECTIONS       — comma-separated section names (default: standard set)
#   EMPHASIS       — free-text guidance on what to highlight
#   OMIT           — comma-separated sections to exclude
#   MODE           — draft | commit | dry-run (default: draft)
#   PRESERVE_HUMAN — true | false (default: true)
#   MODEL          — GitHub Models model ID (default: openai/gpt-4o)

set -uo pipefail

: "${GH_TOKEN:?GH_TOKEN is required}"
: "${TARGET_REPO:?TARGET_REPO is required}"

GITHUB_OWNER="${GITHUB_OWNER:-Interested-Deving-1896}"
AUDIENCE="${AUDIENCE:-developers}"
TONE="${TONE:-technical}"
SECTIONS="${SECTIONS:-}"
EMPHASIS="${EMPHASIS:-}"
OMIT="${OMIT:-}"
MODE="${MODE:-draft}"
PRESERVE_HUMAN="${PRESERVE_HUMAN:-true}"
MODEL="${MODEL:-openai/gpt-4o}"

GH_API="https://api.github.com"
MODELS_API="https://models.github.ai/inference"

info() { echo "[readme-wizard] $*"; }
warn() { echo "[warn] $*" >&2; }

# ── GitHub API helpers ────────────────────────────────────────────────────────

gh_get() {
  curl -sf \
    -H "Authorization: token ${GH_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    "$@"
}

get_file_content() {
  local owner="$1" repo="$2" path="$3"
  local meta
  meta=$(gh_get "${GH_API}/repos/${owner}/${repo}/contents/${path}" 2>/dev/null) || return 1
  echo "$meta" | jq -r '.content // empty' | tr -d '\n' | base64 -d 2>/dev/null
}

get_file_sha() {
  local owner="$1" repo="$2" path="$3"
  gh_get "${GH_API}/repos/${owner}/${repo}/contents/${path}" 2>/dev/null \
    | jq -r '.sha // empty'
}

commit_file() {
  local owner="$1" repo="$2" branch="$3" path="$4" message="$5" content_b64="$6" sha="$7"
  local payload
  if [[ -n "$sha" ]]; then
    payload=$(jq -n \
      --arg m "$message" --arg c "$content_b64" --arg s "$sha" --arg b "$branch" \
      '{message:$m, content:$c, sha:$s, branch:$b}')
  else
    payload=$(jq -n \
      --arg m "$message" --arg c "$content_b64" --arg b "$branch" \
      '{message:$m, content:$c, branch:$b}')
  fi
  curl -sf -X PUT \
    -H "Authorization: token ${GH_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -H "Content-Type: application/json" \
    "${GH_API}/repos/${owner}/${repo}/contents/${path}" \
    -d "$payload" > /dev/null
}

get_default_branch() {
  local owner="$1" repo="$2"
  gh_get "${GH_API}/repos/${owner}/${repo}" 2>/dev/null \
    | jq -r '.default_branch // "main"'
}

create_branch() {
  local owner="$1" repo="$2" branch="$3" from_sha="$4"
  curl -sf -X POST \
    -H "Authorization: token ${GH_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -H "Content-Type: application/json" \
    "${GH_API}/repos/${owner}/${repo}/git/refs" \
    -d "$(jq -n --arg ref "refs/heads/${branch}" --arg sha "$from_sha" \
      '{ref:$ref, sha:$sha}')" > /dev/null
}

get_branch_sha() {
  local owner="$1" repo="$2" branch="$3"
  gh_get "${GH_API}/repos/${owner}/${repo}/git/ref/heads/${branch}" 2>/dev/null \
    | jq -r '.object.sha // empty'
}

open_pr() {
  local owner="$1" repo="$2" branch="$3" base="$4"
  local pr_url
  pr_url=$(curl -sf -X POST \
    -H "Authorization: token ${GH_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    -H "Content-Type: application/json" \
    "${GH_API}/repos/${owner}/${repo}/pulls" \
    -d "$(jq -n \
      --arg title "docs: README wizard output (${AUDIENCE}, ${TONE})" \
      --arg body "Generated by \`readme-wizard.yml\`.\n\n**Audience:** ${AUDIENCE}\n**Tone:** ${TONE}\n**Emphasis:** ${EMPHASIS:-_(none)_}\n**Sections:** ${SECTIONS:-_(standard)_}\n**Omit:** ${OMIT:-_(none)_}\n\nReview and merge when satisfied, or close and re-run with different inputs." \
      --arg head "$branch" \
      --arg base "$base" \
      '{title:$title, body:$body, head:$head, base:$base}')" \
    | jq -r '.html_url // empty')
  echo "$pr_url"
}

# ── Repo context collector ────────────────────────────────────────────────────

collect_context() {
  local owner="$1" repo="$2"
  local context=""

  local meta
  meta=$(gh_get "${GH_API}/repos/${owner}/${repo}" 2>/dev/null) || return 1
  local description language
  description=$(echo "$meta" | jq -r '.description // ""')
  language=$(echo "$meta" | jq -r '.language // ""')
  context+="Repository: ${owner}/${repo}\n"
  context+="Description: ${description}\n"
  context+="Primary language: ${language}\n\n"

  for f in "package.json" "Cargo.toml" "go.mod" "pyproject.toml" "Makefile" "CMakeLists.txt"; do
    local content
    content=$(get_file_content "$owner" "$repo" "$f" 2>/dev/null | head -c 1500) || continue
    [[ -z "$content" ]] && continue
    context+="=== ${f} ===\n${content}\n\n"
  done

  local workflows
  workflows=$(gh_get "${GH_API}/repos/${owner}/${repo}/contents/.github/workflows" 2>/dev/null \
    | jq -r '.[].name' 2>/dev/null | tr '\n' ' ') || true
  [[ -n "$workflows" ]] && context+="Workflows: ${workflows}\n\n"

  local tree
  tree=$(gh_get "${GH_API}/repos/${owner}/${repo}/git/trees/HEAD" 2>/dev/null \
    | jq -r '.tree[].path' 2>/dev/null | head -40 | tr '\n' ' ') || true
  [[ -n "$tree" ]] && context+="Top-level files: ${tree}\n\n"

  echo -e "$context"
}

# ── LLM ──────────────────────────────────────────────────────────────────────

llm_ask() {
  local system_prompt="$1" user_prompt="$2" max_tokens="${3:-4000}"
  local attempt=0 max_retries=3

  while (( attempt < max_retries )); do
    local payload response http_code body
    payload=$(jq -n \
      --arg model  "$MODEL" \
      --arg sys    "$system_prompt" \
      --arg usr    "$user_prompt" \
      --argjson mt "$max_tokens" \
      '{model:$model,messages:[{role:"system",content:$sys},{role:"user",content:$usr}],temperature:0.3,max_tokens:$mt}')

    response=$(curl -s -w "\n%{http_code}" \
      -X POST "${MODELS_API}/chat/completions" \
      -H "Authorization: Bearer ${GH_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "$payload" 2>/dev/null)

    http_code=$(echo "$response" | tail -1)
    body=$(echo "$response" | sed '$d')

    if [[ "$http_code" == "200" ]]; then
      echo "$body" | jq -r '.choices[0].message.content // empty' 2>/dev/null
      return 0
    elif [[ "$http_code" == "429" ]]; then
      local retry_after
      retry_after=$(echo "$body" | jq -r '.retry_after // 60' 2>/dev/null || echo 60)
      warn "Rate limited — sleeping ${retry_after}s (attempt $((attempt+1))/${max_retries})"
      sleep "$retry_after"
      (( attempt++ ))
    else
      warn "LLM call failed (HTTP ${http_code})"
      return 1
    fi
  done
  return 1
}

# ── Section list resolution ───────────────────────────────────────────────────

STANDARD_SECTIONS="what-it-does install usage configuration architecture ci mirror-chain license"

resolve_sections() {
  local requested="$1" omitted="$2"
  local sections

  if [[ -z "$requested" ]]; then
    sections="$STANDARD_SECTIONS"
  else
    sections=$(echo "$requested" | tr ',' '\n' | tr -d ' ' | tr '\n' ' ')
  fi

  # Remove omitted sections
  if [[ -n "$omitted" ]]; then
    for omit_sec in $(echo "$omitted" | tr ',' '\n' | tr -d ' '); do
      sections=$(echo "$sections" | tr ' ' '\n' | grep -v "^${omit_sec}$" | tr '\n' ' ')
    done
  fi

  echo "$sections"
}

# ── README generator ──────────────────────────────────────────────────────────

audience_guidance() {
  case "$AUDIENCE" in
    end-users)      echo "Write for non-technical end users. Avoid jargon. Focus on what the software does and how to use it, not how it works internally." ;;
    ops-sysadmins)  echo "Write for operations engineers and sysadmins. Focus on deployment, configuration, secrets, schedules, and operational concerns." ;;
    mixed)          echo "Write for a mixed audience of developers and end users. Balance technical detail with accessibility." ;;
    *)              echo "Write for software developers. Be precise and technical. Assume familiarity with git, GitHub Actions, and shell scripting." ;;
  esac
}

tone_guidance() {
  case "$TONE" in
    friendly) echo "Use a friendly, approachable tone. Short sentences. Occasional use of 'you' is fine." ;;
    minimal)  echo "Be extremely concise. No filler. Every sentence must carry information. Prefer tables and code blocks over prose." ;;
    *)        echo "Use a neutral, technical tone. No marketing language. No superlatives. Present tense." ;;
  esac
}

generate_readme() {
  local context="$1" existing_readme="$2" sections="$3"

  local preserve_block=""
  if [[ "$PRESERVE_HUMAN" == "true" && -n "$existing_readme" ]]; then
    # Extract all LTS blocks to preserve them verbatim
    local lts_blocks
    lts_blocks=$(echo "$existing_readme" | awk \
      '/<!-- LTS:start:/{found=1} found{print} /<!-- LTS:end:/{found=0}')
    [[ -n "$lts_blocks" ]] && preserve_block="Preserve these existing human-authored sections verbatim (do not modify their content):\n\n${lts_blocks}"
  fi

  local badge_line="[![Built with Ona](https://ona.com/build-with-ona.svg)](https://app.ona.com/#https://github.com/${GITHUB_OWNER}/${TARGET_REPO})"

  local system_prompt
  system_prompt="You are a technical writer creating a README.md for an open-source project.
$(audience_guidance)
$(tone_guidance)
Rules:
- Output only valid Markdown. No preamble, no explanation.
- The very first line after the # title must be this badge line exactly: ${badge_line}
- Use <!-- AI:start:SECTION --> and <!-- AI:end:SECTION --> markers around each AI-owned section.
- Use <!-- LTS:start:SECTION --> and <!-- LTS:end:SECTION --> markers around each human-owned section.
- AI-owned sections: what-it-does, architecture, ci, mirror-chain, contributors
- Human-owned sections: install, usage, configuration, license (and any custom sections)
- No marketing language. No superlatives. Present tense."

  local user_prompt
  user_prompt="Write a README.md for this repository.

Sections to include (in this order): ${sections}
${EMPHASIS:+Emphasis: ${EMPHASIS}}
${preserve_block}

Repository context:
${context}"

  llm_ask "$system_prompt" "$user_prompt" 6000
}

# ── Main ──────────────────────────────────────────────────────────────────────

info "Target: ${GITHUB_OWNER}/${TARGET_REPO}"
info "Audience: ${AUDIENCE} | Tone: ${TONE} | Mode: ${MODE}"
info "Model: ${MODEL}"

# Collect context
info "Collecting repo context..."
context=$(collect_context "$GITHUB_OWNER" "$TARGET_REPO") || {
  warn "Failed to collect repo context — aborting"
  exit 1
}

# Get existing README (if any)
existing_readme=$(get_file_content "$GITHUB_OWNER" "$TARGET_REPO" "README.md" 2>/dev/null) || existing_readme=""
existing_sha=$(get_file_sha "$GITHUB_OWNER" "$TARGET_REPO" "README.md" 2>/dev/null) || existing_sha=""

# Resolve section list
sections=$(resolve_sections "$SECTIONS" "$OMIT")
info "Sections: ${sections}"

# Generate README
info "Generating README..."
new_readme=$(generate_readme "$context" "$existing_readme" "$sections") || {
  warn "README generation failed — aborting"
  exit 1
}

if [[ -z "$new_readme" ]]; then
  warn "LLM returned empty README — aborting"
  exit 1
fi

# Dry-run: print and exit
if [[ "$MODE" == "dry-run" ]]; then
  echo ""
  echo "════════════════════════════════════════════"
  echo "  DRY RUN — generated README for ${TARGET_REPO}"
  echo "════════════════════════════════════════════"
  echo ""
  echo "$new_readme"
  exit 0
fi

new_b64=$(echo "$new_readme" | base64 -w0)
default_branch=$(get_default_branch "$GITHUB_OWNER" "$TARGET_REPO")

if [[ "$MODE" == "draft" ]]; then
  # Create branch and open PR
  wizard_branch="readme-wizard/${TARGET_REPO}"
  base_sha=$(get_branch_sha "$GITHUB_OWNER" "$TARGET_REPO" "$default_branch")

  # Delete existing wizard branch if present (idempotent re-runs)
  curl -sf -X DELETE \
    -H "Authorization: token ${GH_TOKEN}" \
    -H "Accept: application/vnd.github+json" \
    "${GH_API}/repos/${GITHUB_OWNER}/${TARGET_REPO}/git/refs/heads/${wizard_branch}" \
    > /dev/null 2>&1 || true

  info "Creating branch ${wizard_branch}..."
  create_branch "$GITHUB_OWNER" "$TARGET_REPO" "$wizard_branch" "$base_sha"

  info "Committing README to branch..."
  commit_file "$GITHUB_OWNER" "$TARGET_REPO" "$wizard_branch" "README.md" \
    "docs: README wizard draft (${AUDIENCE}, ${TONE})" \
    "$new_b64" ""

  info "Opening PR..."
  pr_url=$(open_pr "$GITHUB_OWNER" "$TARGET_REPO" "$wizard_branch" "$default_branch")
  info "✅ PR opened: ${pr_url}"

elif [[ "$MODE" == "commit" ]]; then
  info "Committing README directly to ${default_branch}..."
  commit_file "$GITHUB_OWNER" "$TARGET_REPO" "$default_branch" "README.md" \
    "docs: README wizard (${AUDIENCE}, ${TONE}) [skip ci]" \
    "$new_b64" "$existing_sha" \
    && info "✅ README committed to ${default_branch}." \
    || { warn "❌ Commit failed"; exit 1; }
fi
