#!/usr/bin/env bash
#
# kport-toolchain.sh — cross-compile toolchain setup
#
# Installs and configures the GNU cross-compilation toolchain for building
# i386, arm64, or riscv64 binaries from an amd64 host.
#
# Usage:
#   bash scripts/kport/kport-toolchain.sh setup <arch>
#   bash scripts/kport/kport-toolchain.sh env   <arch>   # print env vars
#   bash scripts/kport/kport-toolchain.sh check <arch>   # verify toolchain
#   bash scripts/kport/kport-toolchain.sh cmake <arch>   # print CMake toolchain file path
#
# Supported cross targets: i386  arm64  riscv64
# Host requirement: amd64 (x86_64) running Debian/Ubuntu
#
# After setup, source the env output to get:
#   CC, CXX, AR, STRIP, OBJCOPY, RANLIB, PKG_CONFIG
#   CROSS_COMPILE (GNU triple prefix, e.g. aarch64-linux-gnu-)
#   CMAKE_TOOLCHAIN_FILE (path to generated CMake toolchain file)
#
# This file is managed by fork-sync-all/propagate-hw-detect.
# Source: https://github.com/Interested-Deving-1896/KPort

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLCHAIN_DIR="${KPORT_TOOLCHAIN_DIR:-${HOME}/.config/kport/toolchains}"

# ── Arch metadata ─────────────────────────────────────────────────────────────

_triple() {
  case "$1" in
    i386)    echo "i686-linux-gnu" ;;
    arm64)   echo "aarch64-linux-gnu" ;;
    riscv64) echo "riscv64-linux-gnu" ;;
    amd64)   echo "x86_64-linux-gnu" ;;
    *)       echo "" ;;
  esac
}

_debian_arch() {
  case "$1" in
    i386)    echo "i386" ;;
    arm64)   echo "arm64" ;;
    riscv64) echo "riscv64" ;;
    amd64)   echo "amd64" ;;
    *)       echo "" ;;
  esac
}

_apt_packages() {
  local triple="$1"
  echo "gcc-${triple} g++-${triple} binutils-${triple} \
        libgcc-s1-${triple}-cross libstdc++-dev-${triple}-cross \
        linux-libc-dev-${triple}-cross \
        pkg-config-${triple} \
        qemu-user-static binfmt-support"
}

_rust_target() {
  case "$1" in
    i386)    echo "i686-unknown-linux-gnu" ;;
    arm64)   echo "aarch64-unknown-linux-gnu" ;;
    riscv64) echo "riscv64gc-unknown-linux-gnu" ;;
    amd64)   echo "x86_64-unknown-linux-gnu" ;;
    *)       echo "" ;;
  esac
}

# ── CMake toolchain file generator ───────────────────────────────────────────

_write_cmake_toolchain() {
  local arch="$1"
  local triple
  triple=$(_triple "$arch")
  local outfile="${TOOLCHAIN_DIR}/${arch}-linux-gnu.cmake"

  mkdir -p "$TOOLCHAIN_DIR"

  local cmake_system_processor
  case "$arch" in
    i386)    cmake_system_processor="i686" ;;
    arm64)   cmake_system_processor="aarch64" ;;
    riscv64) cmake_system_processor="riscv64" ;;
    amd64)   cmake_system_processor="x86_64" ;;
  esac

  cat > "$outfile" << CMAKEOF
# KPort cross-compilation toolchain for ${arch}
# Generated by kport-toolchain.sh — do not edit manually.
# Source: https://github.com/Interested-Deving-1896/KPort

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR ${cmake_system_processor})

set(CROSS_TRIPLE "${triple}")

find_program(CMAKE_C_COMPILER   NAMES ${triple}-gcc   REQUIRED)
find_program(CMAKE_CXX_COMPILER NAMES ${triple}-g++   REQUIRED)
find_program(CMAKE_AR           NAMES ${triple}-ar     )
find_program(CMAKE_STRIP        NAMES ${triple}-strip  )
find_program(CMAKE_RANLIB       NAMES ${triple}-ranlib )
find_program(CMAKE_OBJCOPY      NAMES ${triple}-objcopy)

set(CMAKE_FIND_ROOT_PATH /usr/${triple})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# pkg-config for cross arch
set(ENV{PKG_CONFIG_PATH}         "/usr/lib/${triple}/pkgconfig:/usr/share/pkgconfig")
set(ENV{PKG_CONFIG_LIBDIR}       "/usr/lib/${triple}/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR}  "")

# KPort hardware tier hints (set by kport-build-flags.sh)
if(DEFINED ENV{KPORT_CPU_TIER})
  set(KPORT_CPU_TIER \$ENV{KPORT_CPU_TIER})
endif()
if(DEFINED ENV{KPORT_GPU_TIER})
  set(KPORT_GPU_TIER \$ENV{KPORT_GPU_TIER})
endif()
if(DEFINED ENV{KPORT_NPU_TIER})
  set(KPORT_NPU_TIER \$ENV{KPORT_NPU_TIER})
endif()
CMAKEOF

  echo "$outfile"
}

# ── Subcommands ───────────────────────────────────────────────────────────────

cmd_setup() {
  local arch="${1:-}"
  [[ -z "$arch" ]] && { echo "Usage: kport-toolchain.sh setup <arch>  (i386|arm64|riscv64)" >&2; exit 1; }

  local triple
  triple=$(_triple "$arch")
  [[ -z "$triple" ]] && { echo "Unsupported arch: ${arch}" >&2; exit 1; }

  echo "[toolchain] Setting up cross toolchain for ${arch} (${triple})..."

  # Install cross packages
  local pkgs
  pkgs=$(_apt_packages "$triple")
  echo "[toolchain] Installing: ${pkgs}"
  # shellcheck disable=SC2086
  sudo apt-get install -y $pkgs

  # Register foreign arch with dpkg (needed for cross-arch sysroot headers)
  if ! dpkg --print-foreign-architectures | grep -q "^$(_debian_arch "$arch")$"; then
    echo "[toolchain] Registering dpkg arch: $(_debian_arch "$arch")"
    sudo dpkg --add-architecture "$(_debian_arch "$arch")"
    sudo apt-get update -qq
  fi

  # Install Rust cross target if rustup is available
  if command -v rustup &>/dev/null; then
    local rust_target
    rust_target=$(_rust_target "$arch")
    echo "[toolchain] Adding Rust target: ${rust_target}"
    rustup target add "$rust_target" || true
  fi

  # Generate CMake toolchain file
  local cmake_file
  cmake_file=$(_write_cmake_toolchain "$arch")
  echo "[toolchain] CMake toolchain file: ${cmake_file}"

  echo "[toolchain] Setup complete for ${arch}."
  echo "[toolchain] Source env with: eval \"\$(bash scripts/kport/kport-toolchain.sh env ${arch})\""
}

cmd_env() {
  local arch="${1:-}"
  [[ -z "$arch" ]] && { echo "Usage: kport-toolchain.sh env <arch>" >&2; exit 1; }

  local triple
  triple=$(_triple "$arch")
  [[ -z "$triple" ]] && { echo "Unsupported arch: ${arch}" >&2; exit 1; }

  local cmake_file="${TOOLCHAIN_DIR}/${arch}-linux-gnu.cmake"
  [[ ! -f "$cmake_file" ]] && cmake_file=$(_write_cmake_toolchain "$arch")

  cat << ENVEOF
export CROSS_COMPILE="${triple}-"
export CC="${triple}-gcc"
export CXX="${triple}-g++"
export AR="${triple}-ar"
export STRIP="${triple}-strip"
export OBJCOPY="${triple}-objcopy"
export RANLIB="${triple}-ranlib"
export PKG_CONFIG="${triple}-pkg-config"
export PKG_CONFIG_PATH="/usr/lib/${triple}/pkgconfig:/usr/share/pkgconfig"
export PKG_CONFIG_LIBDIR="/usr/lib/${triple}/pkgconfig"
export CMAKE_TOOLCHAIN_FILE="${cmake_file}"
export KPORT_CROSS="true"
export KPORT_CROSS_TRIPLE="${triple}"
export KPORT_ARCH="${arch}"
export CARGO_BUILD_TARGET="$(_rust_target "$arch")"
ENVEOF
}

cmd_check() {
  local arch="${1:-}"
  [[ -z "$arch" ]] && { echo "Usage: kport-toolchain.sh check <arch>" >&2; exit 1; }

  local triple
  triple=$(_triple "$arch")
  local ok=true

  echo "[toolchain] Checking cross toolchain for ${arch} (${triple})..."

  for tool in gcc g++ ar strip objcopy ranlib; do
    if command -v "${triple}-${tool}" &>/dev/null; then
      echo "  OK: ${triple}-${tool} ($(${triple}-${tool} --version 2>&1 | head -1))"
    else
      echo "  MISSING: ${triple}-${tool}"
      ok=false
    fi
  done

  if command -v rustup &>/dev/null; then
    local rust_target
    rust_target=$(_rust_target "$arch")
    if rustup target list --installed 2>/dev/null | grep -q "^${rust_target}$"; then
      echo "  OK: Rust target ${rust_target}"
    else
      echo "  MISSING: Rust target ${rust_target} (run: rustup target add ${rust_target})"
      ok=false
    fi
  fi

  local cmake_file="${TOOLCHAIN_DIR}/${arch}-linux-gnu.cmake"
  if [[ -f "$cmake_file" ]]; then
    echo "  OK: CMake toolchain file ${cmake_file}"
  else
    echo "  MISSING: CMake toolchain file (run: kport-toolchain.sh setup ${arch})"
    ok=false
  fi

  $ok && echo "[toolchain] All checks passed for ${arch}." || \
         echo "[toolchain] Some checks failed. Run: bash scripts/kport/kport-toolchain.sh setup ${arch}"
  $ok
}

cmd_cmake() {
  local arch="${1:-}"
  [[ -z "$arch" ]] && { echo "Usage: kport-toolchain.sh cmake <arch>" >&2; exit 1; }
  local cmake_file="${TOOLCHAIN_DIR}/${arch}-linux-gnu.cmake"
  [[ ! -f "$cmake_file" ]] && cmake_file=$(_write_cmake_toolchain "$arch")
  echo "$cmake_file"
}

# ── Dispatch ──────────────────────────────────────────────────────────────────

SUBCMD="${1:-}"
shift || true

case "$SUBCMD" in
  setup) cmd_setup "$@" ;;
  env)   cmd_env   "$@" ;;
  check) cmd_check "$@" ;;
  cmake) cmd_cmake "$@" ;;
  *)
    echo "Usage: kport-toolchain.sh <setup|env|check|cmake> <arch>"
    echo "  setup  <arch>  — install cross toolchain packages"
    echo "  env    <arch>  — print environment variable exports"
    echo "  check  <arch>  — verify toolchain is installed"
    echo "  cmake  <arch>  — print path to CMake toolchain file"
    echo ""
    echo "Supported arches: i386  arm64  riscv64"
    exit 1
    ;;
esac
