name: 107-vagrant-fedora-43

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v6

    - name: Set up brain profile
      run: |
        echo "BRIAN_PROFILE_PATH=/vagrant/brain/profile" >> $GITHUB_ENV

    - name: run buidl and test
      run: |
        ./tests/107-vagrant-fedora-43/vagrant.install.build.test.sh
